### ISSUE TITLE
Add social media icons and links.

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#103]
We'd be creating accounts for tipohiz so there's a need to add link to these account.
namely: github, X, discord

**Comment by sunny7899** [comment]
Hi @JhohannesK I can work on it

**Comment by sunny7899** [comment]
please add hacktoberfest label too on the ticket @JhohannesK

**Comment by JhohannesK** [comment]
@sunny7899 We need our PR corrected asap and add this link to our discord server too.
[https://discord.gg/8Z67Fv8z](https://discord.gg/8Z67Fv8z)

**Comment by sunny7899** [comment]
Sure

**Comment by sunny7899** [comment]
@JhohannesK code pushed
