### ISSUE TITLE
Theme array usability

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#113]
`app/layout` and `components/expo/theme-choose` share the same array for themes

![image](https://github.com/user-attachments/assets/3c3cd061-ec03-487e-b218-36bb25b12512)

Can we export this array so we don't have to repeat ourselves again.
seems having to add your theme to one and forgetting the order causes a theme change bug

**Comment by morph1nX** [comment]
I can work on this. Please assign it to me.

**Comment by JhohannesK** [comment]
How far with this?

**Comment by d-a-ve** [comment]
Yeah, I saw this and I was going to ask what's up.

I can pick it up.

**Comment by d-a-ve** [comment]
I will create a file for themes constants close to the theme provider and export that, so it can be used everywhere
