### ISSUE TITLE
Contributors section on readme doesn't seem to update

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#116]
![image](https://github.com/user-attachments/assets/2376add7-0f64-4cba-adf0-1d052ced0895)

There's also a typo with the name of tipoHiZ.
![image](https://github.com/user-attachments/assets/3f330e4d-5a76-4acc-9090-fd549bb54658)

Things to do:

- [ ] Make the contributor section update in real-time as new people contribute to the project
- [ ] Fix the typo mentioned above

**Comment by iampearlep** [comment]
Can you please assign this to me?

**Comment by Shashank1618** [comment]
HI @JhohannesK you project looks awesome and I want to contribute to your project. Can you please assign this issue to me.

**Comment by iampearlep** [comment]
> @iampearlep reopening this issue....
> 
> Still not working.

I have fixed it, it works fine now, will create another pr

**Comment by iampearlep** [comment]
> @iampearlep reopening this issue....
> 
> Still not working.

I have fixed it, it works fine now.
