### ISSUE TITLE
bug: Shift + Letter Doesn't Capitalize on Typohiz

### ISSUE THREAD

**Issue by masabinhok** [JhohannesK/TipoHiZ#118]
**Issue Title:** Shift + Letter Doesn't Capitalize on Typohiz

**Description:** On the Typohiz typing website, pressing Shift + any letter key doesn't capitalize the letter. Expected behavior is capitalization when Shift is held.

**Steps to Reproduce:**
1. Open Typohiz.
2. Hold the Shift key and press any letter.

**Expected Result:** The letter should appear capitalized.
**Actual Result:** User can't type.

https://github.com/user-attachments/assets/c081a99b-0d17-4531-a449-6a20acb71fc1

**Comment by masabinhok** [comment]
I'll try to fix this.

**Comment by debianbaker** [comment]
I have fixed this issue ;)
[Screencast from 08-10-24 12:43:30 AM IST.webm](https://github.com/user-attachments/assets/4d7f0974-61bc-4628-ae86-fe8d848667f8)
 Should i open the PR @JhohannesK or will @masabinhok do it?

**Comment by JhohannesK** [comment]
@masabinhok , should @debianbaker go ahead with his PR to this issue?
or you're working working on it?

**Comment by masabinhok** [comment]
cool, raise the pr.

**Comment by debianbaker** [comment]
@JhohannesK can you label this issue as hacktoberfest?

**Comment by masabinhok** [comment]
you assigned me again, assign @debianbaker

**Comment by JhohannesK** [comment]
> you assigned me again, assign @debianbaker

my bad
