### ISSUE TITLE
Feature Request: Add Typing Sound for Enhanced Experience

### ISSUE THREAD

**Issue by masabinhok** [JhohannesK/TipoHiZ#119]
Adding typing sounds on Typohiz would enhance user experience by providing auditory feedback and satisfaction during typing. I recently added sound to a js game website, and it brought life to it. I would love to add this feature.

**Comment by JhohannesK** [comment]
This is a great addition.
We could add as an optional thing for user to toggle on or off.

**Comment by NawinKumarSharma** [comment]
@masabinhok  can you please assign me?

**Comment by JhohannesK** [comment]
> @masabinhok can you please assign me?

He wants to work on it by himself.

**Comment by JhohannesK** [comment]
A settings page is being prepared where we would permanently put the toggle.
but you can go on with the implementation.
