### ISSUE TITLE
Add cyberbunk to the array in `app/layout.tsx`

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#121]
There's a bit of a minor issue though...

you need to add `cyberpunk` to the themes array in `app/layout.tsx` also.
else, it causes a bug as mentioned in #104.

_Originally posted by @JhohannesK in https://github.com/JhohannesK/TipoHiZ/issues/102#issuecomment-2393516766_

**Comment by jatinn-sw** [comment]
ill work on this

**Comment by jatinn-sw** [comment]
i fixed it, have a look maybe? #123
