### ISSUE TITLE
[Feat] -  Add Issue Templates

### ISSUE THREAD

**Issue by abhishekHegde2000** [JhohannesK/TipoHiZ#124]
**Description:**
Create issue templates to standardize the format and ensure all necessary information is provided for different types of issues. These templates will be added to the `.github/ISSUE_TEMPLATE/` directory.

**Tasks:**
1. **Create Directory:**
   - If it doesn't already exist, create the `.github/ISSUE_TEMPLATE/` directory.

2. **Create Bug Report Template:**
   - Create a `bug_report.yml` file in the `.github/ISSUE_TEMPLATE/` directory with the necessary template content for bug reports.

3. **Create Feature Request Template:**
   - Create a `feature_request.yml` file in the `.github/ISSUE_TEMPLATE/` directory with the necessary template content for feature requests.

**Files to Modify:**
- Create `.github/ISSUE_TEMPLATE/bug_report.yml`
- Create `.github/ISSUE_TEMPLATE/feature_request.yml`

**Benefits:**
- Standardizes the format for submitting bug reports and feature requests, improving clarity and completeness.
- Facilitates easier and more consistent issue tracking and management within the project.

**Comment by abhishekHegde2000** [comment]
@darkjoka Can you please assign this to me?

**Comment by JhohannesK** [comment]
![image](https://github.com/user-attachments/assets/eacef441-242a-4da9-9f3d-434640642f26)

Is there of excluding this from template if answer is no?

**Comment by abhishekHegde2000** [comment]
@JhohannesK Hi, if somebody chooses no, then it should be assigned to someone else not themselves.
but If you choose yes then you opt into work on this issue

**Comment by JhohannesK** [comment]
> @JhohannesK Hi, if somebody chooses no, then it should be assigned to someone else not themselves. but If you choose yes then you opt into work on this issue

yeah..so I was asking if that section can be excluded from being added when issue is submitted if the person choosed `no`?

**Comment by abhishekHegde2000** [comment]
I am getting confused, can you elaborate it more?

you want me to remove it ?
