### ISSUE TITLE
[Feature] Minor ui issues noticed on smaller screens.

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#127]
### Is your feature request related to a problem/unavailable functionality? Please describe.

* On smaller screens, the pallete is supposed to appear as a drop-down. but the background of the pallete is transparent.
* The time, language and theme does not align on smaller screens.
* Footer becomes a mess on very small screens

### Proposed Solution

* The pallete should have an opaque background like that of themes.

### Screenshots

![image](https://github.com/user-attachments/assets/1be179cf-7836-48da-bb69-8b86b7604282)
![image](https://github.com/user-attachments/assets/ff00f3a9-73aa-43e6-b158-3fa0c72f5d36)
![image](https://github.com/user-attachments/assets/e96afedf-b07f-41e1-ad3a-9622d1133cc7)

**Comment by Sapna127** [comment]
hey, I would like to work on this issue. Please assign it to me.
