### ISSUE TITLE
[FEATURE] Redesign of login/signup button

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#128]
### Is your feature request related to a problem/unavailable functionality? Please describe.

@kwaw_kumi designed this for us.

### Proposed Solution

![image](https://github.com/user-attachments/assets/93f6ffda-9f66-4665-961e-e0b698a8d4c8)

**Comment by vprathap21** [comment]
I'd like to work on this , can you assign me

**Comment by dexterousdhruv** [comment]
@JhohannesK  Do I have to explicitly add the signup button, since it isn't there originally ?
