### ISSUE TITLE
Displaying results

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#13]
A whole page which would be redirected to automatically when the user's time is up; to display the user's result

**Comment by Mefisto04** [comment]
hey @JhohannesK i will design that page and code also with proper code structure, can you assign this issue to me.

**Comment by JhohannesK** [comment]
We currently have a page to show the results but we need a design revamp.

I am speaking a designer to get us an inspiration to use.

Unless you are a designer yourself 😄.

**Comment by Mefisto04** [comment]
yes sure i can try, please assign this work to me so that i can start working on it.

**Comment by Kay-kwaw** [comment]
Hey @JhohannesK I have already started working on the design.

**Comment by JhohannesK** [comment]
> yes sure i can try, please assign this work to me so that i can start working on it.

@Mefisto04 let's see the designer has for us......
he designs this page and you code it..

I'm assigning both of you to this issue

**Comment by Kay-kwaw** [comment]
Great! @Mefisto04 A pleasure to work with you.

**Comment by JhohannesK** [comment]
@Mefisto04 
![image](https://github.com/user-attachments/assets/82eba17d-0b44-45b0-a8b1-26ff3309eb6a)

**Comment by Kay-kwaw** [comment]
something is up?
