### ISSUE TITLE
[FEATURE] Auto-close theme modal when theme is selected.

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#133]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

When a user chooses a new theme, the modal is still kept open unless user closes it or clicks outside of the modal

### Proposed Solution

Auto-close modal when a new theme is selected.

component to find modal:
`components/expo/theme-choose.tsx`

### Do you want to work on this issue?

No

**Comment by d-a-ve** [comment]
Yeah, I can do this. Assign it to me.
