### ISSUE TITLE
[FEATURE] Design for a user settings page.

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#138]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

We would need a page where users able to have some for of personalized features to choose from.
let's caret style, sound (whether on or off, and maybe with different sounds to choose from).
We can also even display all the themes there again.

### Proposed Solution

We need a figma design first to assist us.

### Do you want to work on this issue?

No

**Comment by aribch** [comment]
I would like to work on this task, can you assign it to me please?

**Comment by JhohannesK** [comment]
sure...but let me confirm if the UI guy is preparing some designs..or you meant you want to give us figma design?

**Comment by aribch** [comment]
I thought I needed to make a design in Figma first and if it suits you, then implement it. So the task is to implement the finished design? I'm ready to try to take on this. I don't have much experience in frontend development, but this task is marked as "good first issue" so I would like to try

**Comment by JhohannesK** [comment]
You can go with the designs..

Join our discord and receive and ask for feedback quicker.
https://discord.gg/8Z67Fv8z
