### ISSUE TITLE
While typing, if the type is changed, then the time doesn't reset and the typing stops abruptly.

### ISSUE THREAD

**Issue by debianbaker** [JhohannesK/TipoHiZ#147]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

[Screencast from 07-10-24 07:42:32 PM IST.webm](https://github.com/user-attachments/assets/47c8425a-c391-433a-92a7-ba0211a802bb)

### Steps to Reproduce

Let the type is changed from 'number' to 'punctuation'( for example ) while typing, time doesn't reset and there is abrupt typing stop.

### Screenshots

Expected Behaviour -
[Screencast from 07-10-24 07:50:55 PM IST.webm](https://github.com/user-attachments/assets/17030490-c237-412f-90b5-63ff8754207c)

### Do you want to work on this issue?

Yes

**Comment by debianbaker** [comment]
Can you assign this to me?

**Comment by JhohannesK** [comment]
This happens on preview? or main deployment

**Comment by debianbaker** [comment]
Main deployment has the issue, i have implemented in local dev.

**Comment by JhohannesK** [comment]
I'm been looking to reproduce the bug where the caret goes missing...I think you just discovered that.

**Comment by d-a-ve** [comment]
Finally found the bug. I said it will be found @JhohannesK 

I just tested it out and yeah, it's reproducible everytime. Once the type of words is changed, timer doesn't reset like @debianbaker said and after typing the first word with a space, the caret is lost.

**Comment by debianbaker** [comment]
@d-a-ve Yes. But I found that in local development, the bug is not present. I think it has been removed. 
Btw @JhohannesK what you said about caret is the actual bug. The caret is not visible some times.

**Comment by d-a-ve** [comment]
I think the problem is from the keyboard focus. Once the type is clicked, any keyboard press sends focus back to the type and after space bar, the caret is lost.

The bug is in both production and preview env

**Comment by debianbaker** [comment]
I think it is the problem with activeWord state because the caret is also lost when we restart sometimes.

**Comment by JhohannesK** [comment]
> I think it is the problem with activeWord state because the caret is also lost when we restart sometimes.

yeah, right
sometimes lost when you want to retake.

**Comment by JhohannesK** [comment]
Fixed this in #193
