### ISSUE TITLE
[FEATURE] Add a github Pull request template.

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#156]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

There is not pull request template so contributers tend to miss out to give in-depth information on what their PR really does.

### Proposed Solution

PR should be able to ask contributers questions like how issue template is.
Some questions like:
* What issue does this PR address?
* Description of file changes.
* Checkbox to determine whether PR is still in progress or it's completed.

### Do you want to work on this issue?

No

**Comment by gyauelvis** [comment]
Assign me to this
