### ISSUE TITLE
[FEATURE] Default typing sound to `off` by default

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#162]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

No

### Proposed Solution

The default sound option when you open the website should be off, unless the user wants to hear sounds...they should toggle it themelves.

### Do you want to work on this issue?

No

**Comment by swarupn17** [comment]
Hey @JhohannesK I can do this task. Please can you assign it to me.
Thanks !

**Comment by JhohannesK** [comment]
Join our discord if you haven't already. https://discord.gg/8Z67Fv8z
