### ISSUE TITLE
[BUG] Remove `^` from dependency's version numbers to avoid automatic upates

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#163]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Have ^ attached to the version number means that, those dependencies would automatically update anytime someone wants to install them, for instance, first timers on this project.

### Steps to Reproduce

Include any relevant details like:

### Do you want to work on this issue?

Yes

**Comment by gyauelvis** [comment]
Assign to me
