### ISSUE TITLE
[BUG] Husky pre-commit hook not working for some contributors

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#171]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

With some PRs I recieve, the errors I see clearly shows husky doesn't work for most people working on the project.
This is making people consciously and unsconsciously push bad code. 😞 

### Steps to Reproduce

Include any relevant details like:

To know if husky works on your local.
Try to push and watch your terminal to see other commands run before it commits. If it doesn't, it means husky doesn't work for you.

### Do you want to work on this issue?

Yes

**Comment by bruno-keiko** [comment]
Hi, I want to address this issue as it provides clearer errors for incorrect yml files.

**Comment by JhohannesK** [comment]
> Hi, a husky error occurred in the update-contributors.yml file before, but now the errors are gone. So contributors need to remember to sync their forks and rebase preview branch.

yeah..buh generally
it seems it doesn't run for most people.. so they are able to go ahead and push bad code for review.

**Comment by slashexx** [comment]
It didn't run for me earlier but now that it does work, I get the following message 

![image](https://github.com/user-attachments/assets/e4453836-c8d8-48d9-a616-71c34b4f8bfa)

Maybe we'll need to review the version matching support.
