### ISSUE TITLE
Need a logo for TipoHiZ to use favicon

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#18]

**Comment by darkjoka** [comment]
That current logo looks cool by the way

**Comment by JhohannesK** [comment]
it's just text I made that way o

**Comment by darkjoka** [comment]
I know but it looks "to me" so cool

**Comment by JhohannesK** [comment]
and the favicon?
What do we use?

**Comment by darkjoka** [comment]
I think feather icons would suffice

**Comment by debianbaker** [comment]
Can create a nice logo for TipoHiz. Can you assign this to me?

**Comment by debianbaker** [comment]
![image](https://github.com/user-attachments/assets/039b5a36-fa35-49a0-a749-19ebcc87a056)
Any suggestions? For white theme.

**Comment by JhohannesK** [comment]
Something simple we can use as favicon.

**Comment by debianbaker** [comment]
Ok 👍

**Comment by JhohannesK** [comment]
Hi, @debianbaker 

We need a banner of our logo to add to our readme.
Can we get that, please?

**Comment by JhohannesK** [comment]
Realised you were not in the discord server
https://discord.gg/sHkcYRhY
