### ISSUE TITLE
[FEATURE] Theme color preview on selection 

### ISSUE THREAD

**Issue by mokshanirugutti** [JhohannesK/TipoHiZ#183]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

This is addon to theme selection. This update enable color preview before selecting the theme
![image](https://github.com/user-attachments/assets/6aa84024-80f0-4cad-8644-7cb831730c54)

### Proposed Solution

This feature will add main color codes as preview while selecting the theme 
the end result will look something like this 
![image](https://github.com/user-attachments/assets/6aa2cfe9-7f97-47b8-9e6a-da67198319e2)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

i will make map main colors codes that highlight the theme and display them on  theme selection menu

**Comment by JhohannesK** [comment]
This is great addition @mokshanirugutti .
Let's have it 🙌🏾🙌🏾
