### ISSUE TITLE
[BUG] : Add separator to pallete to differentiate between categories 

### ISSUE THREAD

**Issue by Sahil-Gupta584** [JhohannesK/TipoHiZ#186]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

title i am talking about>
![Screenshot 2024-10-18 110703](https://github.com/user-attachments/assets/8753fbde-ef97-4b0f-9e54-a8d4a33d2aed)

i thing line is a bit confusing to users. Intead this we can just add two dropdowns for timilimits and text lengths.

### Steps to Reproduce

1.Go to homepage 
2. see top titlte and try to click each words

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I wiil add two dropdowns intead of that line and a title above it(some text to look ui good).

**Comment by JhohannesK** [comment]
Use separators instead to separate the different categories.., but leave it as it is

**Comment by JhohannesK** [comment]
if you still want to work on this, drop a like and I'd assign it and change issue title.

**Comment by Sahil-Gupta584** [comment]
> Use separators instead to separate the different categories.., but leave it as it is

ok i will add saperators
