### ISSUE TITLE
Add themes feature 

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#24]
Add various themes where the user can be able to choose from a list of all the themes.

**Comment by darkjoka** [comment]
checkout https://randoma11y.com/. lots of great accessible themes to choose from

**Comment by Cor4zon** [comment]
Please assign it to me :)

**Comment by JhohannesK** [comment]
@Cor4zon You can go ahead and work on it.. buh you should push your changes onto a new branch

**Comment by JhohannesK** [comment]
@Cor4zon Can you leave a message here so I know you are working on this issue?

**Comment by Cor4zon** [comment]
Yes, i am working on that issue
