### ISSUE TITLE
Calculate typing speed

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#59]
This is been treated,
![image](https://github.com/user-attachments/assets/40973e63-255c-4922-9833-cc4fa18b6c4e)

But anyone with a better way of calculating the wpm can suggest and implement.

**Comment by bandhan-majumder** [comment]
We can count the errors and the length of the words user tried to attempt and after subtracting the speed based on the errors will be more accurate I guess. What do you think?

**Comment by JhohannesK** [comment]
> We can count the errors and the length of the words user tried to attempt and after subtracting the speed based on the errors will be more accurate I guess. What do you think?

We can consider this.
We can keep what we already have as a `raw wpm` and use the errors too to get the `accurate wpm`.

**Comment by Mefisto04** [comment]
Subtract the incorrect words from the total before calculating WPM. Since one word is assumed to have 5 characters, you can subtract incorrectWords * 5 from the total TypedEntries. Like function calculateWPM(typedEntries: number, timeInSeconds: number, wrongWords: number): number

**Comment by ismailgunayy** [comment]
I'd like to try to implement this if it's available ✋🏻

**Comment by JhohannesK** [comment]
@bandhan-majumder Will you pick this up?

**Comment by bandhan-majumder** [comment]
I would love to. But I have been assigned 2 tasks already, so it will take time for me. Till then if anyone wants to work on this, please let them😃.

**Comment by AbdurrahmanSogbesan** [comment]
Hi @JhohannesK, i'd like to work on this
