### ISSUE TITLE
Pressing backspace makes caret vanish

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#74]
The whole idea is that backspace shouldn't do anything, but seems like currently, pressing backspace makes the caret.

**Comment by gyauelvis** [comment]
Is the issue is open? On the website feels like its been solved.

**Comment by JhohannesK** [comment]
> Is the issue is open? On the website feels like its been solved.

I have deactivated the backspace for the meantime. but what I'm noticing now is that when you done typing and it takes you to the result and you click `retake`. the cursor vanishes after you hit space.

**Comment by JhohannesK** [comment]
This issue has been addressed...closing it
