### ISSUE TITLE
Hydration Mismatch Issue 

### ISSUE THREAD

**Issue by itzkushagra** [JhohannesK/TipoHiZ#94]
Facing an error where the text content rendered on the server doesn't match the content rendered on the client side, resulting in a "hydration mismatch" during the React rendering process. When using the next-themes library, the theme value is only available after the client-side JavaScript loads. During server-side rendering, the theme might not be set yet, so it initially renders as an empty string (""), which causes the mismatch with the client-rendered theme (e.g., "dark-green"). 
![Issue](https://github.com/user-attachments/assets/8b1cce00-66d8-4504-8e13-3277223fd16b)

**Comment by JhohannesK** [comment]
Assigning this issue to you as discussed on discord.
Thanks
