### ISSUE TITLE
Space out the divider and the texts beneth it

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#99]
![image](https://github.com/user-attachments/assets/17a64205-0aad-4566-8459-5d55f781c842)

you will notice that there's not space between the divider and the text underneath it.

TODO: 

- [x] Add space
- [ ] Add color to the divider to match chosen theme.

**Comment by shiv-0101** [comment]
Hey dude..

Seems pretty good first issue...is there anything else that need edit. ALSO, can you please mention file as well (if any specific)

**Comment by JhohannesK** [comment]
For now, this is what is available, you can also go through and see what you can also notice.
Designs are also being prepared for some other pages, so you can stay tuned for those pages also if you're interested in the implementing UI.

**Comment by shiv-0101** [comment]
sure dude then let's goo..

also, share the page/component after u assign...

**Comment by JhohannesK** [comment]
> sure dude then let's goo..
> 
> also, share the page/component after u assign...

check `footer.tsx`

**Comment by sunny7899** [comment]
hi @JhohannesK  cab you assign social link task to me

**Comment by shiv-0101** [comment]
> hi @JhohannesK cab you assign social link task to me

Working on it...

**Comment by Sahil-Gupta584** [comment]
@JhohannesK  Is this issue done or i can work on it?

**Comment by JhohannesK** [comment]
One task completed, one other remaining.

**Comment by Sahil-Gupta584** [comment]
> One task completed, one other remaining.

i think 1st task is to space out divider and texts below it , and 2nd one is to give color to divider which is also done ig. because divider color is already matching with theme(dark) or I have to match color for all theme ig?

**Comment by JhohannesK** [comment]
yeah, match to all theme

**Comment by Sahil-Gupta584** [comment]
@JhohannesK Can I solve both my issue with same single pr?

**Comment by JhohannesK** [comment]
Yeah sure.. link both issues to PR when you are done
